Repository SWM-YouQuiz/Quizit-FE, pull requests merged in 2023-08, with the labels that each got.

#18 [YOUQ-113] 로그인
  package.json
  src/app/api/auth/[...nextauth]/route.ts
  src/app/api/auth/register/route.ts
  src/app/auth/input.tsx
  src/app/auth/layout.tsx
  src/app/auth/login/login-form.tsx
  src/app/auth/login/page.tsx
  src/app/auth/register/allow-push/body-container.tsx
  src/app/auth/register/allow-push/page.tsx
  src/app/auth/register/email/body-container.tsx
  src/app/auth/register/email/page.tsx
  src/app/auth/register/layout.tsx
  src/app/auth/register/next-button.tsx
  src/app/auth/register/nickname-password/body-container.tsx
  src/app/auth/register/nickname-password/page.tsx
  src/app/auth/register/provider.tsx
  src/app/auth/register/register-form.tsx
  src/app/globals.css
  src/app/header.tsx
  src/app/page.tsx
  src/app/signout-button.tsx
  src/components/ui/Button.tsx
  src/modules/auth/apiServices.ts
  src/modules/auth/auth.ts
  src/modules/auth/next-auth.d.ts
  src/modules/auth/types.d.ts
  src/modules/types.d.ts
  src/util/fetcher.ts
  src/util/tailwind.ts
Labels: Feat

#21 [YOUQ-115] API 연동
  next.config.js
  src/app/api/auth/register/route.ts
  src/app/auth/register/allow-push/body-container.tsx
  src/app/chapter/[courseName]/card.tsx
  src/app/chapter/layout.tsx
  src/app/curriculum/[curriculumId]/[courseId]/card.tsx
  src/app/curriculum/[curriculumId]/[courseId]/page.tsx
  src/app/curriculum/[curriculumId]/card.tsx
  src/app/curriculum/[curriculumId]/page.tsx
  src/app/curriculum/layout.tsx
  src/app/page.tsx
  src/app/quiz/[chapterId]/[quizId]/explanation-sheet.tsx
  src/app/quiz/[chapterId]/[quizId]/explanation.tsx
  src/app/quiz/[chapterId]/[quizId]/input.tsx
  src/app/quiz/[chapterId]/[quizId]/page.tsx
  src/app/quiz/[chapterId]/[quizId]/quiz-items.tsx
  src/app/quiz/[chapterId]/[quizId]/quiz-swiper.tsx
  src/app/quiz/[chapterId]/[quizId]/quiz.tsx
  src/app/quiz/[chapterId]/page.tsx
  src/app/quiz/[id]/input.tsx
  src/app/quiz/[id]/page.tsx
  src/app/quiz/[id]/quiz-swiper.tsx
  src/app/quiz/error.tsx
  src/modules/auth/apiServices.ts
  src/modules/auth/auth.ts
  src/modules/chapter/chapterDummy.ts
  src/modules/chapter/types.d.ts
  src/modules/course/courseDummy.ts
  src/modules/course/types.d.ts
  src/modules/curriculum/serverApiActions.ts
  src/modules/curriculum/types.d.ts
  src/modules/quiz/explanationDummy.ts
  src/modules/quiz/getQuizComponentsAction.tsx
  src/modules/quiz/hooks/useOptionState.ts
  src/modules/quiz/hooks/useQuizState.ts
  src/modules/quiz/quizDummy.ts
  src/modules/quiz/serverApiActions.ts
  src/modules/quiz/types.d.ts
  src/util/fetcher.ts
  src/util/session.ts
  yarn.lock
Labels: Feat

#27 [YOUQ-116] CI/CD 파이프라인 연동
  Dockerfile
  Jenkinsfile
Labels: ci/cd

#29 [#28] 디자인 적용
  next.config.js
  package.json
  src/app/curriculum/[curriculumId]/[courseId]/[courseTitle]/page.tsx
  src/app/curriculum/[curriculumId]/[courseId]/card.tsx
  src/app/curriculum/[curriculumId]/[courseId]/page.tsx
  src/app/curriculum/[curriculumId]/card.tsx
  src/app/curriculum/[curriculumId]/page.tsx
  src/app/curriculum/layout.tsx
  src/app/curriculum/page.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/app/quiz/[chapterId]/[quizId]/explanation.tsx
  src/app/quiz/[chapterId]/[quizId]/input.tsx
  src/app/quiz/[chapterId]/[quizId]/page.tsx
  src/app/quiz/[chapterId]/[quizId]/quiz-items.tsx
  src/app/quiz/[chapterId]/[quizId]/quiz-swiper.tsx
  src/app/quiz/[chapterId]/[quizId]/quiz.tsx
  src/app/quiz/[chapterId]/page.tsx
  src/app/quiz/layout.tsx
  src/components/Header.tsx
  src/components/svgs/alert.svg
  src/components/svgs/backarrow.svg
  src/components/svgs/filter.svg
  src/components/svgs/heart.svg
  src/components/svgs/heartwhite.svg
  src/components/svgs/index.ts
  src/components/svgs/send.svg
  src/components/svgs/share.svg
  src/components/svgs/thumbdown.svg
  src/components/svgs/thumbup.svg
  src/modules/curriculum/components/Card.tsx
  src/util/font/PretendardVariable.woff2
  tailwind.config.js
  yarn.lock
Labels: Feat

#31 [#30] Input이 키보드에 가려지는 버그 수정
  next.config.js
  package.json
  src/app/curriculum/[curriculumId]/[courseId]/[courseTitle]/page.tsx
  src/app/quiz/[chapterId]/[quizId]/explanation.tsx
  src/modules/quiz/styles/one-light.css
  yarn.lock
Labels: Fix

#37 [YOUQ-137] 커리큘럼 API 연동
  package.json
  src/app/curriculum/[curriculumId]/[courseId]/page.tsx
  src/app/curriculum/[curriculumId]/page.tsx
  src/app/curriculum/page.tsx
  src/app/page.tsx
  src/app/profile/page.tsx
  src/components/svgs/index.ts
  src/components/svgs/rightarrow.svg
  src/modules/auth/serverApiActions.ts
  src/modules/curriculum/serverApiActions.ts
  src/modules/curriculum/types.d.ts
  src/modules/profile/CalendarHeatmap.tsx
  src/modules/profile/styles/calendarHeatmap.css
  yarn.lock
Labels: Feat
